<!DOCTYPE html>
<html lang="es">
<!-- La cabecera -->

<head>
<meta charset="UTF-8" />
<meta name="generator" content="Sublime-Text" />
<meta name="author" content="Héctor - Roberto "/>
<meta name="keywords" content="HTML5, web" />
<meta name="description" content="PI - HOME" />

<link rel="stylesheet" type="text/css" href="css/home.css" title="Estilo principal" />
<link rel="alternate stylesheet" type="text/css" href="css/contrast.css"
 title="Estilo de escala de grises" />
<link rel="alternate stylesheet" type="text/css" href="css/big.css"
 title="Estilo de tamaño grande" />
<link rel="stylesheet" type="text/css" href="css/print.css" media="print" />

<script src="javascript/script.js"></script>
<script src="javascript/scriptRegistro.js"></script>
<script src="javascript/scriptOrdenacion.js"></script>
<script src="javascript/cookies.js"></script>

<title>PI - HOME</title>
</head>
<!-- El cuerpo -->


<body onload="readStyle(); cargar();" onunload="saveStyle();">
<!--<body onload="iniciar()";>-->
<br>