<header id="cab_principal">
  <a href="index.php"><img src="images/logo1.png"  alt="foto"></a>
  <nav>
        <ul class="menu">  
           <li><a href="busqueda.html">Busqueda Avanzada</a></li>  
            <li>
                 Apariencia
                 <ul>
                    <li><a href="#" onclick="setActiveStyleSheet('Estilo principal'); return false;">Estilo Principal</a></li>
                    <li><a href="#" onclick="setActiveStyleSheet('Estilo de escala de grises'); return false;">Estilo Alternativo</a></li>    
                </ul>
          
           </li>

        </ul>    
  </nav> 
  </header>

  </header>
