<header id="cab_principal">
  <a href="index.php"><img src="images/logo1.png"  alt="foto"></a>
  <br>
  <li><a href="#" onclick="setActiveStyleSheet('Estilo principal'); return false;">Estilo Principal</a></li>
  <br>
  <li><a href="#" onclick="setActiveStyleSheet('Estilo de escala de grises'); return false;">Estilo alternativo</a></li>

  <nav>
        <ul class="menu">  
            <li><a href="busqueda.php">Busqueda Avanzada</a></li>      
        </ul>    
  </nav> 
  </header>
