	<sidebar>

	 <div id="sideBg">

	 	<div id="sideCont">
	 	<div id="latBg"></div>
	 	<div id="lat">
	 		<img id="logo" src="images/logo1.png"  alt="foto">
	 		<img id="avatar" src="images/avatar.jpg" >
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Portafolio</a></li>
            <li><a href="#">Productos</a></li>
            <li><a href="#">Contacto</a></li>
        </ul>
    	</div>
    </div>
	</div>
    

</sidebar>